import "./style.scss"
import "./scripts/healthAPI"
import "./scripts/worldAPI"
import "./scripts/travelAPI"
import "./scripts/sportsAPI"
import "./scripts/businessAPI"
import "./scripts/settings"
import "./scripts/toggle"